spring:
  application:
    name: idat-estudiante

########## H2SQL #################
h2:
  console:
    enabled: true
datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  username: root
  password: 123456
  driver-class-name: org.h2.Driver
