
spring:
  application:
    name: servicio-producto

########## MYSQL #################
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/idat
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
